mqtt:
  climate:
    - name: Bedroom AC (LG LP1017WSR)
      unique_id: smarter_ac_unit
      qos: 0
      optimistic: true
      modes:
        - "off"
        - "cool"
      fan_modes:
        - "high"
        - "low"
      min_temp: 60
      max_temp: 86
      initial: 70
      temperature_unit: F
      temp_step: 1
      mode_command_topic: "smarter_ac_unit/mode/set"
      mode_command_template: "{{ value if value == 'off' else 'on' }}"
      mode_state_topic: "smarter_ac_unit/mode/state"
      fan_mode_command_topic: "smarter_ac_unit/fan/set"
      fan_mode_state_topic: "smarter_ac_unit/fan/state"
      temperature_command_topic: "smarter_ac_unit/temperature/set"
      temperature_state_topic: "smarter_ac_unit/temperature/state"
